IF OBJECT_ID('dbo.Bottle', 'U') IS NOT NULL
DROP TABLE dbo.Bottle
GO
CREATE TABLE dbo.Bottle
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Distillery [NVARCHAR](200) NOT NULL,
    Name [NVARCHAR](200) NOT NULL,
    Age INT NULL,
    Description [NVARCHAR](2000) NOT NULL
);
GO
ALTER TABLE Bottle ALTER COLUMN Description [NVARCHAR](2000) NULL
GO