IF OBJECT_ID('dbo.Event', 'U') IS NOT NULL
DROP TABLE dbo.Event
GO
CREATE TABLE dbo.Event
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    LocationId UNIQUEIDENTIFIER NOT NULL,
    Title [NVARCHAR](200) NOT NULL,
    Description [NVARCHAR](2000) NOT NULL,
    Date DATETIME NOT NULL,
    FOREIGN KEY (LocationId) REFERENCES Location(Id)
);
GO
ALTER TABLE Event ALTER COLUMN Description [NVARCHAR](2000) NULL
GO