IF OBJECT_ID('dbo.Location', 'U') IS NOT NULL
DROP TABLE dbo.Location
GO
CREATE TABLE dbo.Location
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name [NVARCHAR](200) NOT NULL,
    Address1 [NVARCHAR](2000) NOT NULL,
    Address2 [NVARCHAR](2000) NOT NULL,
    City [NVARCHAR](2000) NOT NULL,
    State [NVARCHAR](2000) NOT NULL,
    ZipCode INT NOT NULL
);
GO
ALTER TABLE Location ALTER COLUMN Address2 [NVARCHAR](2000) NULL
GO