// flow-typed signature: 62c0ab65037ec114e8252c886401e16a
// flow-typed version: <<STUB>>/eslint-config-payscale_v^0.0.5/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-payscale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-payscale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-payscale/index' {
  declare module.exports: $Exports<'eslint-config-payscale'>;
}
declare module 'eslint-config-payscale/index.js' {
  declare module.exports: $Exports<'eslint-config-payscale'>;
}
