// flow-typed signature: 3454fcae17ba30da7d3bbf544e048019
// flow-typed version: <<STUB>>/react-native-root-modal_v^1.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-root-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-root-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-root-modal/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-native-root-modal/lib/ModalContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-root-modal/lib/Modal.js' {
  declare module.exports: $Exports<'react-native-root-modal/lib/Modal'>;
}
declare module 'react-native-root-modal/lib/ModalContainer.js' {
  declare module.exports: $Exports<'react-native-root-modal/lib/ModalContainer'>;
}
