export const LOAD_BOTTLES = 'LOAD_BOTTLES';
export const BOTTLES_LOADED = 'BOTTLES_LOADED';
export const ADD_BOTTLE = 'ADD_BOTTLE';
export const BOTTLE_ADDED = 'BOTTLE_ADDED';
export const BOTTLE_SELECTED = 'BOTTLE_SELECTED';
